# Generated by Django 2.2.20 on 2021-09-29 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cultivador',
                'verbose_name_plural': 'Cultivadores',
            },
            bases=('backend.customuser',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
            bases=('backend.customuser',),
        ),
        migrations.CreateModel(
            name='PatientCultivator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente Autocultivador',
                'verbose_name_plural': 'Pacientes Autocultivadores',
            },
            bases=('backend.customuser',),
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Cultivator')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Patient')),
                ('patient_cultivator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.PatientCultivator')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('patient', 'doctor', 'cultivator', 'patient_cultivator')},
            },
        ),
    ]
