# Generated by Django 3.2.7 on 2021-09-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210929_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(max_length=200, verbose_name='Obra Social'),
        ),
    ]
