# Generated by Django 3.2.7 on 2021-10-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
